# Generated by Django 4.1.13 on 2025-07-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коллектива')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фестиваля')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('description', models.TextField(blank=True, verbose_name='Описание фестиваля')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название места')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('концерт', 'Концерт'), ('спектакль', 'Спектакль'), ('опера', 'Опера'), ('форум', 'Форум'), ('концерт старинной музыки', 'Концерт старинной музыки'), ('органный концерт', 'Органный концерт'), ('концерт классической музыки', 'Концерт классической музыки'), ('концерт симфонической музыки', 'Концерт симфонической музыки'), ('концерт народной музыки', 'Концерт народной музыки'), ('театрально музыкальная постановка', 'Театрально музыкальная постановка'), ('балет', 'Балет'), ('цирк', 'Цирк'), ('виртуальный концерт', 'Виртуальный концерт'), ('музыкальная сказка для детей', 'Музыкальная сказка для детей'), ('шоу программа', 'Шоу программа'), ('танцы', 'Танцы')], max_length=50, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('ticket_url', models.CharField(max_length=500, verbose_name='Купить билет')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('ensembles', models.ManyToManyField(to='postapp.ensemble', verbose_name='Коллектив')),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postapp.festival', verbose_name='Фестиваль')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.venue', verbose_name='Место проведения')),
            ],
        ),
    ]
