# Generated by Django 4.1.13 on 2025-07-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_alter_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='festival',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ensembles',
            field=models.ManyToManyField(blank=True, to='postapp.ensemble', verbose_name='Коллектив'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Купить билет'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postapp.venue', verbose_name='Место проведения'),
        ),
    ]
